### ISSUE TITLE
telethon.errors.common.MultiError: ([FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest

### ISSUE THREAD

**Issue by Willizemp** [Kazama009/Telegram-Scrapper-Adder#1]
[+] Fetching Members...
Traceback (most recent call last):
  File "/home/sonofgrace/Telegram-Scrapper-Adder/scraper.py", line 79, in <module>
    all_participants = client.get_participants(target_group, aggressive=True)
  File "/home/sonofgrace/.local/lib/python3.9/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/sonofgrace/.local/lib/python3.9/site-packages/telethon/client/chats.py", line 507, in get_participants                                      
    return await self.iter_participants(*args, **kwargs).collect()           
  File "/home/sonofgrace/.local/lib/python3.9/site-packages/telethon/requestiter.py", line 113, in collect                                                
    async for message in self:                                               
  File "/home/sonofgrace/.local/lib/python3.9/site-packages/telethon/requestiter.py", line 74, in __anext__                                               
    if await self._load_next_chunk():                                        
  File "/home/sonofgrace/.local/lib/python3.9/site-packages/telethon/client/chats.py", line 222, in _load_next_chunk                                      
    results = await self.client(self.requests)                               
  File "/home/sonofgrace/.local/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__                                               
    return await self._call(self._sender, request, ordered=ordered)          
  File "/home/sonofgrace/.local/lib/python3.9/site-packages/telethon/client/users.py", line 80, in _call                                                  
    raise MultiError(exceptions, results, requests)                          
telethon.errors.common.MultiError: ([FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), None, None, FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 23 seconds is required (caused by GetParticipantsRequest)')], [None, <telethon.tl.types.channels.ChannelParticipants object at 0x7f23aba707c0>, None, None, None, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x7f23ab987820>, <telethon.tl.types.channels.ChannelParticipants object at 0x7f23abbc9c40>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc5ee20>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc5eee0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc5efa0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc630a0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63160>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63220>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc632e0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc633a0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63460>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63520>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc635e0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc636a0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63760>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63820>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc638e0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc639a0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63a60>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63b20>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63be0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63ca0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63d60>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63e20>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63ee0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abc63fa0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abbe50a0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x7f23abbe5160>])

**Comment by DonEros** [comment]
experiencing the same issue.

**Comment by fourbearscourses** [comment]
@Kazama009
